# Generated by Django 3.2.9 on 2021-12-06 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='total_experience',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
