# Generated by Django 3.2.9 on 2021-12-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculation', '0002_candidate_total_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='candidate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='calculation.candidate'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='end',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start',
            field=models.CharField(max_length=60),
        ),
    ]
